version: '2'
services:
    jhipster-app:
        image: jhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://jhipster-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipster
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipster-elasticsearch:9300
        ports:
            - 8080:8080
    jhipster-mongodb:
        extends:
            file: mongodb.yml
            service: jhipster-mongodb
    jhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
